-- ─── Human-friendly order numbers ────────────────────────────────────────────
-- Every appointment gets a short, unambiguous order number (e.g. AV-7K4M2Q) that
-- the post-checkout Quo SMS sends to the customer. They redeem it on /order to
-- view status, pay the balance, or reschedule — no login required. Generated by
-- a BEFORE INSERT trigger so all booking paths (webhook, verify, manual) share it.

alter table public.appointments add column if not exists order_number text;

-- 6 chars from a no-confusion alphabet (no 0/O/1/I), prefixed AV-.
create or replace function public.gen_order_number()
returns text
language plpgsql
as $$
declare
  alphabet constant text := '23456789ABCDEFGHJKMNPQRSTUVWXYZ';
  code text;
  collision boolean;
begin
  loop
    code := 'AV-' || (
      select string_agg(substr(alphabet, (floor(random() * length(alphabet)) + 1)::int, 1), '')
      from generate_series(1, 6)
    );
    select exists(select 1 from public.appointments where order_number = code) into collision;
    exit when not collision;
  end loop;
  return code;
end;
$$;

create or replace function public.set_order_number()
returns trigger
language plpgsql
as $$
begin
  if new.order_number is null or btrim(new.order_number) = '' then
    new.order_number := public.gen_order_number();
  end if;
  return new;
end;
$$;

drop trigger if exists appointments_set_order_number on public.appointments;
create trigger appointments_set_order_number
  before insert on public.appointments
  for each row execute function public.set_order_number();

create unique index if not exists appointments_order_number_key
  on public.appointments(order_number);

-- Backfill any rows created before this migration.
update public.appointments
  set order_number = public.gen_order_number()
  where order_number is null or btrim(order_number) = '';
