import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Check, CreditCard, Loader2, RefreshCw, RotateCcw } from 'lucide-react';
import AdminShell from '@/components/admin/AdminShell';
import { apiGet, apiPatch } from '@/lib/apiClient';

const money = (cents, currency = 'USD') => new Intl.NumberFormat('en-US', { style: 'currency', currency }).format(Number(cents || 0) / 100);
const FILTERS = [['all', 'All'], ['unmatched', 'Unmatched'], ['failed', 'Failed'], ['refunded', 'Refunds']];

export default function ClientPayments() {
  const [state, setState] = useState({ loading: true, error: '', payments: [], metrics: {}, candidates: {} });
  const [filter, setFilter] = useState('all');
  const [range, setRange] = useState('month');
  const [editing, setEditing] = useState(null);
  const [association, setAssociation] = useState({ appointmentId: '', eventContainerId: '', eventServiceId: '', invoiceReference: '' });
  const load = useCallback(async () => {
    setState((current) => ({ ...current, loading: true, error: '' }));
    try { const data = await apiGet(`/api/admin/client-payments?range=${range}&includeCandidates=1`); setState({ loading: false, error: '', payments: data.payments || [], metrics: data.metrics || {}, candidates: data.candidates || {} }); }
    catch (error) { setState((current) => ({ ...current, loading: false, error: error.message })); }
  }, [range]);
  useEffect(() => { load(); }, [load]);
  const rows = useMemo(() => state.payments.filter((row) => filter === 'all' || (filter === 'unmatched' && row.reconciliation_status === 'unmatched') || (filter === 'failed' && row.status === 'failed') || (filter === 'refunded' && row.refunded_cents > 0)), [state.payments, filter]);
  const act = async (paymentId, action, extra = {}) => {
    try { await apiPatch('/api/admin/client-payments', { paymentId, action, ...extra }); setEditing(null); setAssociation({ appointmentId: '', eventContainerId: '', eventServiceId: '', invoiceReference: '' }); await load(); }
    catch (error) { setState((current) => ({ ...current, error: error.message })); }
  };
  return (
    <AdminShell title="Client payments">
      <div className="space-y-5">
        <header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-foreground/45">Square reconciliation</p><h1 className="font-heading text-4xl uppercase">Client payments</h1></div><div className="flex gap-2"><select value={range} onChange={(e) => setRange(e.target.value)} className="min-h-10 rounded-full border border-foreground/10 bg-background px-4 text-xs font-bold uppercase"><option value="today">Today</option><option value="week">7 days</option><option value="month">This month</option><option value="all">All</option></select><button onClick={load} className="flex h-10 w-10 items-center justify-center rounded-full border border-foreground/10"><RefreshCw className={`h-4 w-4 ${state.loading ? 'animate-spin' : ''}`} /></button></div></header>
        <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[['Captured', money(state.metrics.completedCents)], ['Refunded', money(state.metrics.refundedCents)], ['Unmatched', state.metrics.unmatched || 0], ['Failed', state.metrics.failed || 0]].map(([label, value]) => <div key={label} className="rounded-2xl border border-foreground/10 bg-foreground/[0.035] p-4"><p className="text-[9px] font-bold uppercase tracking-[0.18em] text-foreground/45">{label}</p><p className="mt-2 font-heading text-3xl">{value}</p></div>)}</div>
        {state.error ? <p className="rounded-2xl bg-red-500/10 p-4 text-sm text-red-700">{state.error}</p> : null}
        <div className="flex gap-1 overflow-x-auto rounded-2xl border border-foreground/10 p-1">{FILTERS.map(([key, label]) => <button key={key} onClick={() => setFilter(key)} className={`min-h-10 rounded-xl px-4 text-[10px] font-bold uppercase tracking-[0.14em] ${filter === key ? 'bg-foreground text-background' : 'text-foreground/55'}`}>{label}</button>)}</div>
        <div className="grid gap-3">{rows.map((payment) => <article key={payment.id} className="rounded-2xl border border-foreground/10 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><CreditCard className="h-4 w-4" /><p className="font-semibold">{money(payment.amount_cents, payment.currency)}</p><span className="text-[10px] font-bold uppercase tracking-[0.12em] text-foreground/45">{payment.status}</span></div><p className="mt-1 text-xs text-foreground/50">{payment.provider_payment_id} · {payment.location_id || 'No location'} · {payment.source || 'unknown source'}</p><p className="mt-1 text-xs text-foreground/50">{payment.processed_at ? new Date(payment.processed_at).toLocaleString() : 'Pending timestamp'}</p></div><div className="text-right"><span className={`inline-flex rounded-full border px-2.5 py-1 text-[10px] font-bold uppercase tracking-[0.12em] ${payment.reconciliation_status === 'matched' ? 'border-emerald-500/30 text-emerald-700' : 'border-amber-500/30 text-amber-700'}`}>{payment.reconciliation_status}</span>{payment.refunded_cents > 0 ? <p className="mt-2 text-xs text-red-700"><RotateCcw className="mr-1 inline h-3.5 w-3.5" />{money(payment.refunded_cents, payment.currency)} refunded</p> : null}</div></div>
          {payment.reconciliation_status === 'matched' ? <div className="mt-3 flex flex-wrap items-center justify-between gap-2 rounded-xl bg-foreground/[0.035] p-3 text-xs"><span>Matched by {payment.match_method}: {payment.appointment_id || payment.event_container_id || payment.event_service_id || payment.invoice_reference}</span>{payment.match_method === 'manual' ? <button onClick={() => act(payment.id, 'unmatch')} className="font-bold uppercase tracking-[0.12em]">Unmatch</button> : null}</div> : null}
          {payment.reconciliation_status === 'unmatched' ? <div className="mt-3"><button onClick={() => setEditing(editing === payment.id ? null : payment.id)} className="min-h-10 rounded-full bg-foreground px-4 text-[10px] font-bold uppercase tracking-[0.12em] text-background"><AlertTriangle className="mr-1 inline h-3.5 w-3.5" />Reconcile</button>{editing === payment.id ? <div className="mt-3 grid gap-2 rounded-2xl bg-foreground/[0.035] p-3 md:grid-cols-2"><select className="min-h-11 rounded-xl border border-foreground/10 bg-background px-3 text-sm" value={association.appointmentId} onChange={(e) => setAssociation({ appointmentId: e.target.value, eventContainerId: '', eventServiceId: '', invoiceReference: '' })}><option value="">Appointment…</option>{(state.candidates.appointments || []).map((row) => <option key={row.id} value={row.id}>{row.order_number || row.id} · {row.protocol_key || 'visit'}</option>)}</select><select className="min-h-11 rounded-xl border border-foreground/10 bg-background px-3 text-sm" value={association.eventContainerId} onChange={(e) => setAssociation({ appointmentId: '', eventContainerId: e.target.value, eventServiceId: '', invoiceReference: '' })}><option value="">Event…</option>{(state.candidates.events || []).map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select><input className="min-h-11 rounded-xl border border-foreground/10 bg-background px-3 text-sm" placeholder="Invoice reference" value={association.invoiceReference} onChange={(e) => setAssociation({ appointmentId: '', eventContainerId: '', eventServiceId: '', invoiceReference: e.target.value })} /><div className="flex gap-2"><button onClick={() => act(payment.id, 'match', association)} className="min-h-11 flex-1 rounded-xl bg-foreground text-[10px] font-bold uppercase text-background"><Check className="mr-1 inline h-3.5 w-3.5" />Match</button><button onClick={() => act(payment.id, 'ignore')} className="min-h-11 rounded-xl border border-foreground/10 px-4 text-[10px] font-bold uppercase">Ignore</button></div></div> : null}</div> : null}
        </article>)}{state.loading ? <p className="flex items-center gap-2 p-6 text-sm"><Loader2 className="h-4 w-4 animate-spin" />Loading Square payments</p> : null}{!state.loading && !rows.length ? <p className="rounded-2xl border border-dashed border-foreground/15 p-10 text-center text-sm text-foreground/45">No payments in this view. Unmatched payments are never hidden.</p> : null}</div>
      </div>
    </AdminShell>
  );
}

